id: P009530
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W23700
  title: རི་ཆོས་མཚམས་ཀྱི་ཞལ་གདམས
  author: ''
  volumes:
    110710366362496b80125c762d022ea1:
      image_group_id: I2496
      title: ''
      volume_number: 1
      total_pages: 609
      base_file: v001.txt
